name: 'Setup Nix'
description: 'Install Nix'

inputs:
  skip-space-reclaimation:
    description: 'Skip the reclaiming space for nix'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: wimpysworld/nothing-but-nix@main
      if: github.event.inputs.skip-space-reclaimation != 'true' && runner.os == 'Linux'
      with:
        nix-permission-edict: true

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v33
      with:
        nix_version: "2.31.0"
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G

        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-last-accessed: 0
        purge-primary-key: never
