name: 'Setup Lix'
description: 'Install Lix'

inputs:
  github-token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Install Lix
      shell: bash
      run: |
        if ! command -v nix >/dev/null 2>&1; then
          echo "Installing Lix..."
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | \
            sh -s -- install --no-confirm
        else
          echo "Nix/Lix already installed"
        fi

    - name: Configure Lix
      shell: bash
      run: |
        mkdir -p ~/.config/nix

        # Add access token to get around rate-limiting
        if [ -n "${{ inputs.github-token }}" ]; then
          echo "access-tokens = github.com=${{ inputs.github-token }}" >> ~/.config/nix/nix.conf
        fi

    - name: Add Lix to PATH
      shell: bash
      run: echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH
