name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          skip-space-reclaimation: 'true'
      - name: Check lint
        run: nix build .#checks.x86_64-linux.pre-commit-check

  darwin:
    needs: lint # delay until we know the lint is ok
    runs-on: macos-latest
    strategy:
      matrix:
        host: [strongbad, CW-HM9D4MQMW2-L]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Build nix-darwin configuration
        uses: ./.github/actions/nix-build
        with:
          build-target: .#darwinConfigurations.${{ matrix.host }}.system
          job-name: "Darwin (${{ matrix.host }})"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  hm:
    needs: lint # delay until we know the lint is ok
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ["bbennett@bbennett-1"]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Build home-manager configuration
        uses: ./.github/actions/nix-build
        with:
          build-target: .#homeConfigurations.${{ matrix.host }}.activationPackage
          job-name: "Home Manager (${{ matrix.host }})"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  nixos-arm:
    needs: lint # delay until we know the lint is ok
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        host: [devvm]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Build nixos configuration
        uses: ./.github/actions/nix-build
        with:
          build-target: .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
          job-name: "NixOS (${{ matrix.host }})"
          github-token: ${{ secrets.GITHUB_TOKEN }}
